//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGerPro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisGerProEntities : DbContext
    {
        public SisGerProEntities()
            : base("name=SisGerProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atividades> Atividades { get; set; }
        public virtual DbSet<Etapas> Etapas { get; set; }
        public virtual DbSet<Pessoa_Projetos> Pessoa_Projetos { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<Projetos> Projetos { get; set; }
    }
}
