//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGerPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa_Projetos
    {
        public int id_PessoaProjetos { get; set; }
        public int id_Pessoa { get; set; }
        public int id_Projeto { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        public virtual Projetos Projetos { get; set; }
    }
}
