//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisGerPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projetos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projetos()
        {
            this.Etapas = new HashSet<Etapas>();
            this.Pessoa_Projetos = new HashSet<Pessoa_Projetos>();
        }
    
        public int id_Projeto { get; set; }
        public string Nome { get; set; }
        public int id_Pessoa_Responsavel { get; set; }
        public bool Finalizado { get; set; }
        public Nullable<System.DateTime> DtInicio { get; set; }
        public Nullable<System.DateTime> DtFim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etapas> Etapas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa_Projetos> Pessoa_Projetos { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}
